version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - images/*
    - devResume.pdf
    - portfolio_Large.css
    - portfolio_Medium.css
    - portfolio_Small.css
    - dist/bundle.js
